//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_tbl
    {
        public int StudID { get; set; }
        public string StudName { get; set; }
        public string StudAddress { get; set; }
        public string StudCity { get; set; }
        public string StudPhone { get; set; }
        public string StudPassword { get; set; }
    }
}
