//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks_tbl
    {
        public int ID { get; set; }
        public int StudID { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> Mark { get; set; }
    }
}
